package com.example.clicknote.domain.model

enum class ServiceType {
    ONLINE_TRANSCRIPTION,
    OFFLINE_TRANSCRIPTION,
    COMBINED_TRANSCRIPTION,
    AUDIO_ENHANCEMENT,
    SPEAKER_DETECTION,
    SUMMARY_GENERATION
} 